name : mern-app

services:

  
  mongo:
    image: mongo:7.0.12
    ports:
      - ${MONGO_PORT}:27017
    volumes: 
       - ${MONGO_DATA_PATH}:/data/db
    networks:
      - mern-network

  api:
    depends_on:
      - mongo
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - ${API_PORT}:8080
    networks:
      - mern-network

volumes:
  mongo_data:

networks:
  mern-network:
    driver: bridge